apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gateway-whoami-route-https
  namespace: gateway-whoami
spec:
  parentRefs:
    - name: gateway-whoami-gateway
      sectionName: https
  rules:
    - backendRefs:
        - name: gateway-whoami-service
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gateway-whoami-route-http
  namespace: gateway-whoami
spec:
  parentRefs:
    - name: gateway-whoami-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301