apiVersion: v1
kind: Service
metadata:
  namespace: gateway-whoami
  name: gateway-whoami-service
spec:
  type: ClusterIP
  selector:
    app: gateway-whoami
  ports:
    - port: 80
      targetPort: 2001
      protocol: TCP

