apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ngf-whoami-cert
  namespace: ngf-whoami
spec:
  secretName: ngf-whoami-cert-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "ngf-whoami.gcp.xy678.vip"