apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ngf-whoami-route-https
  namespace: ngf-whoami
spec:
  parentRefs:
    - name: ngf-whoami-gateway
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /whoami
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ngf-whoami-service
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ngf-whoami-route-http
  namespace: ngf-whoami
spec:
  parentRefs:
    - name: ngf-whoami-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
