apiVersion: v1
kind: Service
metadata:
  namespace: ngf-whoami
  name: ngf-whoami-service
spec:
  type: ClusterIP
  selector:
    app: ngf-whoami
  ports:
    - port: 80
      targetPort: 2001
      protocol: TCP

